#!/usr/bin/env python2
# -*- coding:utf-8 -*-

# -----------------------------------------------------------------------------
# Getting Things Gnome! - A personal organizer for the GNOME desktop
# Copyright (c) 2008,2009,2010 Lionel Dricot & Bertrand Rousseau
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

"""
Getting Things Gnome! - A personal organizer for the GNOME desktop
==================================================================

:copyright: 2008,2009,2010 Lionel Dricot & Bertrand Rousseau
:license: GNU General Public License, version 3 or later
"""

import sys
from optparse import OptionParser


def X_is_running():
    from gtk.gdk import Screen
    try:
        if Screen().get_display():
            return True
    except RuntimeError:
        pass
    return False


try:
    parser = OptionParser()
    parser.add_option('-b', '--boot-test', action='store_true', dest='boot_test',
      help="Exit immediately after completing boot-up actions", default=False)
    parser.add_option('-c', '--no-crash-handler', action='store_true', dest='no_crash_handler',
      help="Disable the automatic crash handler", default=False)
    parser.add_option('-d', '--debug', action='store_true', dest='debug',
      help="Enable debug output", default=False)
    parser.add_option('-v', '--version', action='store_true', dest='version_and_exit',
      help="Print GTG's version number", default=False)
    (options, args) = parser.parse_args()

    if options.version_and_exit:
        from GTG import info
        print "gtg (Getting Things Gnome!) %s" %(info.VERSION)
        print
        print "For more information: %s" %(info.URL)
        sys.exit(0)

    elif not X_is_running():
        print "Could not open X display"
        sys.exit(1)

    else:
        import GTG.gtg
        sys.exit(GTG.gtg.main(options, args))

except KeyboardInterrupt:
    sys.exit(1)
