#!/usr/bin/env python2
# -*- coding:utf-8 -*-
# -----------------------------------------------------------------------------
# Getting Things GNOME! - A personal organizer for the GNOME desktop
# Copyright (c) 2008-2013 Lionel Dricot & Bertrand Rousseau
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

""" This script creates a new task and launches the editor to display it. """

import cgi
import dbus
import re
import sys

from optparse import OptionParser

from GTG import _


def new_task(title, body):
    """ Open a new task in GTG with given title and body """
    bus = dbus.SessionBus()
    proxy = bus.get_object("org.gnome.GTG", "/org/gnome/GTG")
    gtg = dbus.Interface(proxy, "org.gnome.GTG")
    gtg.OpenNewTask(title, body)


def main():
    """ Parse arguments and create a new task """
    parser = OptionParser()
    parser.add_option('-i', '--interactive', action='store_true',
                      dest='interactive',
                      help=_("Use input as the text of a new task"),
                      default=False)
    (options, args) = parser.parse_args()

    title = " ".join(args)
    if options.interactive:
        body = sys.stdin.read()
        subject_regex = re.compile("^Subject: (.*)$", re.M | re.I)
        if subject_regex.search(body):
            subject = subject_regex.findall(body)[0]
            title = title + ": " + subject
    else:
        body = ""
    new_task(title, cgi.escape(body))

if __name__ == "__main__":
    main()
