#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------
# Gettings Things Gnome! - a personal organizer for the GNOME desktop
# Copyright (c) 2008-2009 - Lionel Dricot & Bertrand Rousseau
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

"""Runs the GTG unit tests."""

import sys
import unittest

from GTG.tests import test_suite

TEST_MODULE_PREFIX = "GTG.tests."

def main(args):
    runner = unittest.TextTestRunner(
                    stream = sys.stdout,
                    descriptions = True,
                    verbosity = 1)
    if len(args) > 0:
        #if we have specified the name of the test in the command line
        suites = []
        for module_name in args:
            #load the module
            module_path = TEST_MODULE_PREFIX + module_name
            module = __import__(module_path)
            sys.modules[module_path] = module
            globals()[module_path] = module
            tests = getattr(module, "tests")
            a_test = getattr(tests, module_name)
            suites.append(getattr(a_test, "test_suite")())
    else:
        #otherwise, run all tests
        suites = [test_suite()]

    #run the tests
    tests_are_successful = True
    for suite in suites:
        result = runner.run(suite)
        tests_are_successful &= result.wasSuccessful()

    #show the aggregated result of all the tests
    if tests_are_successful:
        print "ALL TESTS ARE SUCCESSFUL"
    else:
        print """
        ****************************************
        SOME TESTS *FAILED*!
        ****************************************
        """
    return tests_are_successful


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
