.TH gtg 1 2009-03-21 "gtg"
.SH NAME
gtg \-  Getting Things Gnome!, an organizer for the GNOME desktop
.SH SYNOPSIS
.B gtg
.SH DESCRIPTION
Getting Things GNOME! is an organizer for the GNOME desktop environment.
GTG focuses on usability and ease of use. Its main objective is to
provide a simple and yet flexible organization tool for life and work.
.PP
GTG uses a very handy system for creating and editing tasks. The task editor
can automatically recognize metadata such as tags and subtasks only by the use
of a very simple syntax.
.SH COPYRIGHT
This manual page is Copyright 2009 Luca Falavigna <dktrkranz@debian.org>.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 or any later
version published by the Free Software Foundation.
