.TH GTG_NEW_TASK 1 "4 December 2009"
.SH NAME
gtg_new_task \- Adds a task to the \fBGetting Things GNOME!\fP organizer
.SH SYNOPSIS
\fBgtg_new_task\fP [\-h | \-\-help] [\-i | \-\-interactive]
.SH DESCRIPTION
\fBgtg_new_task\fP creates a new task in the Getting Things GNOME! organizer
for the GNOME desktop via the DBUS message bus.  Getting Things GNOME! must be
running for the command to work.
.SS Options
.TP
\fB[\-h | \-\-help]\fP
Shows a brief usage help.
.TP
\fB[\-i | \-\-interactive]\fP
Accepts a task description via stdin.
.SH FILES
None
.SH "SEE ALSO"
gtg (1)
.SH BUGS
Please report any bug you may experience to the \fBGTG\fP Developers, that can
be reached at \fRhttps://edge.launchpad.net/gtg\fP
.SH COPYRIGHT
This manual page is Copyright2009 Luca Invernizzi <invernizzi.l@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU General Public License, Version 3 or any later version
published by the Free Software Foundation.

