#!/bin/bash
# gtcli bash completion
# -----------------------------------------------------------------------------
# Getting Things GNOME! - A personal organizer for the GNOME desktop
# Copyright (c) 2010 Luca Invernizzi <invernizzi.l@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

#source this file to make it work, or include this line in your ~/.bashrc:
# . /path_to_this_file

_gtcli_completion()
{
   local cur

        COMPREPLY=()
        cur=`_get_cword`

        if [ $COMP_CWORD -eq 1 ]; then
            COMPREPLY=( $( compgen -W '-h  --help new show  edit  delete list
            count postpone close search' -- $cur ) )
        else
            _filedir '@(rar|RAR)'
                fi
        return 0
}
complete -F _gtcli_completion gtcli
