#!/usr/bin/env python
# -*- coding:utf-8 -*-

# -----------------------------------------------------------------------------
# Getting Things Gnome! - A personal organizer for the GNOME desktop
# Copyright (c) 2008,2009 Lionel Dricot & Bertrand Rousseau
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

"""
GTG stress test
"""
import sys
import dbus
import uuid

def connect():
    #We will connect on the session bus
    bus = dbus.SessionBus()
    liste = bus.list_names()
    busname = "org.GTG"
    remote_object = bus.get_object(busname,"/org/GTG")
    return dbus.Interface(remote_object,dbus_interface="org.GTG")

if __name__ == '__main__':
    if len(sys.argv) == 1:
         print "Usage: " + sys.argv[0] + " <number-of-tasks>"
         sys.exit(1)
    total_tasks = int(sys.argv[1])
    gtg = connect()
    for i in xrange(total_tasks):
        gtg.new_task("Active", str(uuid.uuid4()), "","","","","","")
