name: getting-things-gnome
base: core24
compression: lzo
grade: stable
license: GPL-3.0
adopt-info: gtg
confinement: strict

apps:
  gtg:
    command: usr/bin/gtg
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages
    common-id: org.gnome.GTG
    plugs:
      - network
    slots:
      - dbus-service

slots:
  dbus-service:
    interface: dbus
    name: org.gnome.GTG
    bus: session

parts:
  gtg:
    source: .
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - gettext
      - itstool
      - meson
    parse-info:
      - usr/share/metainfo/org.gnome.GTG.metainfo.xml
    stage:
      - usr/bin/gtg
      - usr/lib/python3/
      - usr/share/
    override-build: |
      craftctl default
      sed -i $CRAFT_PART_INSTALL/usr/share/applications/org.gnome.GTG.desktop \
        -e 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.gnome.GTG.svg|'
    after:
      - python-deps

  python-deps:
    plugin: python
    build-packages:
      - python3-dbus
    python-packages:
      - lxml==5.1.0
      - caldav==1.3.9
      - Cheetah3
