# Generate a development Flatpak every friday at midnight

on:
  schedule:
  - cron: "0 0 * * 5"

name: Weekly Development Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    # Need to specify 24.04 until it becomes stable and we can use "latest"
    # again
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: org.gnome.GTG.Devel.flatpak
        manifest-path: build-aux/org.gnome.GTG.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
